version: "3.8"
services:
  portfolio-postgres:
    image: postgres:16
    container_name: portfolio-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - portfolio_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  portfolio_data:

networks:
  portfolio-network:
    driver: bridge
