"""remove_subscribers_table

Revision ID: 7cfbf8e01cc1
Revises: cd43d7f4111b
Create Date: 2025-08-06 19:01:21.181933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cfbf8e01cc1"
down_revision: Union[str, Sequence[str], None] = "cd43d7f4111b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscribers")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscribers",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("status", sa.VARCHAR(), nullable=True),
        sa.Column(
            "subscribed_at",
            sa.DATETIME(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DATETIME(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscribers_email"), "subscribers", ["email"], unique=True)
    op.create_index(op.f("ix_subscribers_id"), "subscribers", ["id"], unique=False)
    # ### end Alembic commands ###
