name: Test Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/test-backend.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/test-backend.yml"

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
          SECRET_KEY: test-secret-key
          SENDGRID_API_KEY: test-key
          SENDGRID_FROM_EMAIL: test@example.com
        run: |
          pytest tests/ -v --tb=short

      - name: Run backend linting
        working-directory: ./backend
        run: |
          python -m flake8 app/ --max-line-length=88 --extend-ignore=E203,W503
          python -m black --check app/
